// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7s5Ijao2HlnZSCoirCuSvoPi6KB9rxtg',
    appId: '1:476868542135:web:929228befb3559053a1732',
    messagingSenderId: '476868542135',
    projectId: 'invist-bh-b3e2b',
    authDomain: 'invist-bh-b3e2b.firebaseapp.com',
    storageBucket: 'invist-bh-b3e2b.firebasestorage.app',
    measurementId: 'G-5WXT253VCZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMpFB_wokh3AGcYAOLmgjK5kEbjKDH7r4',
    appId: '1:476868542135:android:eaf840ef32f4785d3a1732',
    messagingSenderId: '476868542135',
    projectId: 'invist-bh-b3e2b',
    storageBucket: 'invist-bh-b3e2b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4DJ228a9Im8N-yN2KgBhWvuaRRhmQUog',
    appId: '1:476868542135:ios:deb425a98652f6233a1732',
    messagingSenderId: '476868542135',
    projectId: 'invist-bh-b3e2b',
    storageBucket: 'invist-bh-b3e2b.firebasestorage.app',
    iosBundleId: 'com.example.invistBh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4DJ228a9Im8N-yN2KgBhWvuaRRhmQUog',
    appId: '1:476868542135:ios:deb425a98652f6233a1732',
    messagingSenderId: '476868542135',
    projectId: 'invist-bh-b3e2b',
    storageBucket: 'invist-bh-b3e2b.firebasestorage.app',
    iosBundleId: 'com.example.invistBh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7s5Ijao2HlnZSCoirCuSvoPi6KB9rxtg',
    appId: '1:476868542135:web:85ffd1ded75cc6e53a1732',
    messagingSenderId: '476868542135',
    projectId: 'invist-bh-b3e2b',
    authDomain: 'invist-bh-b3e2b.firebaseapp.com',
    storageBucket: 'invist-bh-b3e2b.firebasestorage.app',
    measurementId: 'G-N9NTV36YMZ',
  );
}
